[tool.poetry]
name = "ms-co2-penalty"
version = "0.1.0"
description = ""
authors = ["Lukas Hörtnagl <lukas.hoertnagl@usys.ethz.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
jupyterlab = ">=4.2.4"
pyyaml = "^6.0.2"
geopandas = "^1.1.1"
geodatasets = "^2024.8.0"
scikit-posthocs = "^0.11.4"
openmeteo-requests = "^1.7.5"
requests-cache = "^1.3.0"
retry-requests = "^2.0.0"

[tool.poetry.group.dev.dependencies]
diive = { path = "../../21 - DIIVE/diive", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
