# Dirs
DIR_DATA: ../data
DIR_DATA_SOURCEFILES: ../data/source
DIR_DATA_PARQUET: ../data/parquet/merged
DIR_DATA_PARQUET_SUBSET: ../data/parquet/subset
DIR_DATA_OUT: ../data/output
DIR_DATA_OUT_SITEINFO: ../data/output/03_siteinfo
DIR_DATA_OUT_SHAPVALS_SITE: ../data/output/04_shap_values_site

ECOSYSTEMS: ['DBF', 'DNF', 'EBF', 'ENF', 'MF']

# ICOS (European sites)
PATTERN_DIR_ICOS: ['ICOSETC_', '_ARCHIVE_L2']
PATTERN_FILE_HH_ICOS: ICOSETC_*_FLUXNET_HH_L2.csv

# FLUXNET (European sites)
PATTERN_DIR_FXN: ['FLX_', 'FLUXNET2015_FULLSET_']
PATTERN_FILE_HH_FXN: FLX_*_FLUXNET2015_FULLSET_HH_*.csv
INFOFILE_FXN: ../config/FLUXNET_SitesList_20240404.csv

# AMERIFLUX
PATTERN_DIR_AMF: ['AMF_', 'FLUXNET_FULLSET_']
PATTERN_FILE_HH_AMF: AMF_*_FLUXNET_FULLSET_HH_*.csv
INFOFILE_AMF: ../config/AMERIFLUX_AA-Flx_FLUXNET-BIF_CCBY4_20241205.csv
