# Dirs

#DIR_DATA: ../data
DIR_DATA_PROC_PARQUET: ../../data/outputs/10_datasets/12_parquet_merged
DIR_DATA_PROC_PARQUET_PLOTS: ../../data/outputs/10_datasets/12_parquet_merged_plots
DIR_DATA_PROC_SUBSETS: ../../data/outputs/20_subsets/21_subsets_parquet
DIR_DATA_PROC_SUBSETS_PLOTS: ../../data/outputs/20_subsets/21_subsets_parquet_plots
#DIR_DATA_OUT: ../data/outputs
DIR_DATA_OUT_SHAP_ANALYSIS: ../../data/outputs/30_shap

# Files
ECOSYSTEMS: ['DBF', 'DNF', 'EBF', 'ENF', 'MF']

# JAPANFLUX (JapanFlux2024 dataset)
DIR_DATA_RAW_JPF: ../../data/00_raw/japanflux
PATTERN_DIR_JPF: ['JPF_']
PATTERN_FILE_HH_JPF: FLX_*_JapanFLUX2024_ALLVARS_HH_*.csv
INFOFILE_JPF: ../../data/00_raw/japanflux/0-info/JapanFlux2024_SiteList_20250910.csv

# ICOS (from Carbon Portal)
DIR_DATA_RAW_ICOS: ../../data/00_raw/icos
PATTERN_DIR_ICOS: ['ICOSETC_', '_ARCHIVE_L2']
PATTERN_FILE_HH_ICOS: ICOSETC_*_FLUXNET_HH_L2.csv

# FLUXNET (from Carbon Portal)
DIR_DATA_RAW_FXN_CP: ../../data/00_raw/fluxnet_from_carbonportal
PATTERN_DIR_FXN_CP: ['FLX_', 'FLUXNET2015_FULLSET_']
PATTERN_FILE_HH_FXN_CP: FLX_*_FLUXNET2015_FULLSET_HH_*.csv
INFOFILE_FXN_CP: ../../data/00_raw/fluxnet_from_carbonportal/0-info/FLUXNET_SitesList_20240404.csv

# FLUXNET (from fluxnet.org)
DIR_DATA_RAW_FXN_ORG: ../../data/00_raw/fluxnet_from_fluxnetorg
PATTERN_DIR_FXN_ORG: ['FLX_', 'FLUXNET2015_FULLSET_']
PATTERN_FILE_HH_FXN_ORG: FLX_*_FLUXNET2015_FULLSET_HH_*.csv
INFOFILE_FXN_ORG: ../../data/00_raw/fluxnet_from_fluxnetorg/0-info/FLX_AA-Flx_BIF_HH_20200501.csv

# AMERIFLUX
DIR_DATA_RAW_AMF: ../../data/00_raw/ameriflux
PATTERN_DIR_AMF: ['AMF_', 'FLUXNET_FULLSET_']
PATTERN_FILE_HH_AMF: AMF_*_FLUXNET_FULLSET_HH_*.csv
INFOFILE_AMF: ../../data/00_raw/ameriflux/0-info/AMF_AA-Flx_FLUXNET-BIF_CCBY4_20250804.csv

