BASEDIR: "F:/Sync/luhk_work/40 - DATA/Datasets/2024 - FLUXNET ICOS FORESTS"
#BASEDIR: "F:/Sync/luhk_work/40 - DATA/Datasets/2024 - FLUXNET ICOS FORESTS/__TESTSET__"
OUTDIR: "OUT"
#ECOSYSTEMS: ['ENF']
ECOSYSTEMS: ['DBF', 'DNF', 'EBF', 'ENF', 'MF']
PATTERN_FILE_HH_ICOS: "ICOSETC_*_FLUXNET_HH_L2.csv"
PATTERN_FILE_HH_FXN: "FLX_*_FLUXNET2015_FULLSET_HH_*.csv"
PATTERN_DIR_FXN: ['FLX_', 'FLUXNET2015_FULLSET_']
PATTERN_DIR_ICOS: ['ICOSETC_', '_ARCHIVE_L2']
