BASEDIR: "F:/Sync/luhk_work/40 - DATA/DATASETS/2025_FORESTS"
OUTDIR: "OUT"
ECOSYSTEMS: ['DBF', 'DNF', 'EBF', 'ENF', 'MF']

# ICOS (European sites)
PATTERN_DIR_ICOS: ['ICOSETC_', '_ARCHIVE_L2']
PATTERN_FILE_HH_ICOS: "ICOSETC_*_FLUXNET_HH_L2.csv"

# FLUXNET (European sites)
PATTERN_DIR_FXN: ['FLX_', 'FLUXNET2015_FULLSET_']
PATTERN_FILE_HH_FXN: "FLX_*_FLUXNET2015_FULLSET_HH_*.csv"

# AMERIFLUX
PATTERN_DIR_AMF: ['AMF_', 'FLUXNET_FULLSET_']
PATTERN_FILE_HH_AMF: "AMF_*_FLUXNET_FULLSET_HH_*.csv"
